### PR TITLE
Added lower and upper bounds for initialScreenIndex in RegistrationWo…

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4304

#### Changes proposed in this Pull Request:

- Added lower and upper bounds for initialScreenIndex in RegistrationWorkflow

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- yarn start:example2
- In RegistrationWorkflowScreen try changing initialScreenIndex value to either less than 0 or more than 2

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by daileytj** [comment]
Looks good. want to add a test case for this real quick?

**Comment by surajeaton** [comment]
> Looks good. want to add a test case for this real quick?

@daileytj  Done. Please review.

**Comment by surajeaton** [comment]
@ektaghag-eaton @manojleaton @JeffGreiner-eaton Can you please review?

**Review by ektaghag-eaton — APPROVED** [review]
Working fine 👍

**Pull request merged**
