### PR TITLE
Fix ErrorManager bugs

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-4570.

#### Changes proposed in this Pull Request:

- add default dialog config title
- add default message box position
- add default on close function
- fix object merging on full screens

#### To Test:

- Modify the errorConfig on the Auth or registration providers and/or modify the errorDisplayConfig on individual full screens to modify how errors are displayed. You will need to throw a new error from the corresponding auth or registration actions if you want to test a specific screens error state e.g., the login method on the login screen.

#### Any specific feedback you are looking for?

These are the items in the issue description that need to be tested...

- If we pass 'errorDisplayConfig' props, the error UI will get render in the screen even though error is not there.
**note:** this is how the error manager works and it's not a bug. If an error is provided it will render the error. If the end user wants to manage errors to this degree they will also need to manage the entire flow for showing and hiding the error. This is demonstrated in the advanced usage section of the error-manager component documentation.
- If we pass only 'error' prop in the errorDisplayConfig, application will break since 'title' prop is undefined in 'dialogConfig' prop.
- If we pass 'message-box' as prop to 'mode', application will break since 'position' prop is undefined in the 'messageBoxConfig' prop.
- Default onClose event is not defined.

### CODE REVIEW

**Review by ektaghag-eaton — COMMENTED** [review]
Below are working fine
1. If we pass only 'error' prop in the errorDisplayConfig, application will break since 'title' prop is undefined in 'dialogConfig' prop.

Screenshot 2023-08-18 at 4 47 50 PM

2. If we pass 'message-box' as prop to 'mode', application will break since 'position' prop is undefined in the 'messageBoxConfig' prop.
Screenshot 2023-08-18 at 4 50 02 PM

**Review by ektaghag-eaton — COMMENTED** [review]
If I click on close icon of message box, it is not closing the message box
Screenshot 2023-08-18 at 4 50 02 PM

is it correct?

**Comment by daileytj** [comment]
> If I click on close icon of message box, it is not closing the message box Screenshot 2023-08-18 at 4 50 02 PM
> 
> is it correct?

It depends on what you are doing to get that to work. Can you provide the code you used to make this example?

**Comment by daileytj** [comment]
@ektaghag-eaton 
Screenshot 2023-08-18 at 7 46 04 AM
I'm doing this and it's dismissing just fine. If you provide an "error" to the config then its always going to show the error until you manually remove the error.

**Comment by ektaghag-eaton** [comment]
> @ektaghag-eaton Screenshot 2023-08-18 at 7 46 04 AM I'm doing this and it's dismissing just fine. If you provide an "error" to the config then its always going to show the error until you manually remove the error.

Got it @daileytj, I was passing an `error` prop to the config. Without `error` prop it is dismissible.

**Comment by ektaghag-eaton** [comment]
Working fine 👍

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
