### PR TITLE
Feature/4681 fix workflow card instructions scroll

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4681

#### Changes proposed in this Pull Request:

- Moved workflow card instructions outside workflow card body
- Updated styles and docs

#### Screenshots / Screen Recording (if applicable)

- Screenshot 2023-08-31 at 7 14 06 PM

#### To Test:

- cd login-workflow
- yarn start:example
- Check all the screens which are using workflow card

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by surajeaton** [comment]
> all looks good except for forgot password screen, no styles
> 
> image

Fixed. Please review.

**Review by joebochill — COMMENTED** [review]
Make sure you update the files in the /docs folder to reflect the new expectation for how screens should be constructed (moving the Instructions outside of the body — there is at least one file, customization, that documents this).

**Comment by surajeaton** [comment]
> Make sure you update the files in the /docs folder to reflect the new expectation for how screens should be constructed (moving the Instructions outside of the body — there is at least one file, customization, that documents this).

update workflow-card.md

**Review by ektaghag-eaton — COMMENTED** [review]
Please check styling (padding) below 900px.
Screenshot 2023-09-04 at 3 31 59 PM

**Comment by ektaghag-eaton** [comment]
> > Please check styling (padding) below 900px. Screenshot 2023-09-04 at 3 31 59 PM
> 
> @ektaghag-eaton Updated the PR. Please review
XS is still have same issue.
Screenshot 2023-09-05 at 12 04 09 PM

**Comment by surajeaton** [comment]
> > > Please check styling (padding) below 900px. Screenshot 2023-09-04 at 3 31 59 PM
> > 
> > 
> > @ektaghag-eaton Updated the PR. Please review
> > XS is still have same issue.
> 
> Screenshot 2023-09-05 at 12 04 09 PM

Updated the PR. Please review.

**Comment by ektaghag-eaton** [comment]
Screenshot 2023-09-05 at 3 24 06 PM
Working fine

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
