### PR TITLE
Ensure that individual WorkflowCard props can be provided/extended without having to provide them all

### PR DESCRIPTION
**Pull request by manojleaton**
Fixes # [BLUI-4387](https://jira-prod.tcc.etn.com/browse/BLUI-4387).

#### Changes proposed in this Pull Request:

- Refactored the workflow card action calls in the full screen components

#### To Test:

- yarn start:example2
- Pass WorkflowCardAction props to the full screen components from the example2 components

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
Not part of this PR but the verify code screen data is not retained on navigate.

**Comment by surajeaton** [comment]
> Not part of this PR but the verify code screen data is not retained on navigate.

I will ask @RaghavendranC-Eaton to look into it, as he is working on it.

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good to me

**Review by surajeaton — APPROVED** [review]
Looks good.

**Pull request merged**
