### PR TITLE
Bug/4649 420 change password success screen

### LINKED ISSUE #420: change password workflow is missing a success screen
## Describe the bug / expected behavior

The change password workflow (the one you get after logging in, not the reset password one) currently does not have a success screen. The users will simply suddenly get logged out with no context.

## What are the steps to reproduce?

1. Run example project
2. Log in
3. Change your password via the user menu 
4. Observe that you are suddenly logged out with no warning.

## Your environment information

Mac OS Chrome

## Suggestion

I expect this behavior to be configurable — adopter teams can choose to toggle off this confirmation screen if they need to. But the success screen needs to be there by default.

## Anything else to add?
The forgot password workflow handled this correctly.

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #420 BLUI-4649

#### Changes proposed in this Pull Request:

- Added Success screen to change password dialog
- Added new props for change password dialog

#### Screenshots / Screen Recording (if applicable)

https://github.com/etn-ccis/blui-react-workflows/assets/120575281/3de64283-d606-4498-924b-6f8304522d3f

#### To Test:

- cd login-workflow
- yarn start:example
- enter email and password and login
- click on profile dropdown (upper right corner)
- click on Change Password
- Enter the fields in  Change Password and click on Okay

#### Any specific feedback you are looking for?

- Test cases will be added soon
- Open this PR once #450 gets merged.
- Change base branch once opened this PR
- This PR is to test success screen on change password dialog

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
Noticed the change password dialog is open before its called from menu.


Uploading a-success.mov…

**Comment by JeffGreiner-eaton** [comment]
In the deployed version of PR we have a scroll bar in container but not on local...strange

image

**Comment by surajeaton** [comment]
> In the deployed version of PR we have a scroll bar in container but not on local...strange
> 
> image

Weird, not seeing the scroll on deployed one:

https://github.com/etn-ccis/blui-react-workflows/assets/120575281/a8dbc1f9-989c-4b66-bd38-2321e7c61b32

**Comment by surajeaton** [comment]
> I didn't see it on the deployed branch either, but I see this on deployed branch, mobile:
> 
> image

This should be an issue with success screen. We can create a separate bug/task to track that. @ektaghag-eaton Can you please cover this as a point of smoke test?

**Review by ektaghag-eaton — COMMENTED** [review]
@surajeaton , can you update docs for new prop?

**Comment by surajeaton** [comment]
> @surajeaton , can you update docs for new prop?

Updated. Please review.

**Comment by JeffGreiner-eaton** [comment]
not sure if you updated everything or not but figured I put this here for now. change password dialog onSubmit issue


https://github.com/etn-ccis/blui-react-workflows/assets/119693939/8b6d9fc8-d3b8-4479-8462-e6f39663153e

**Comment by surajeaton** [comment]
> not sure if you updated everything or not but figured I put this here for now. change password dialog onSubmit issue
> 
>  changePswdDialog.mov

Fixed now. Please review.

**Comment by ektaghag-eaton** [comment]
> Noticed the change password dialog is open before its called from menu. If I cancel change password and logout from menu then log back in the change password dialog does not open at login. So might be tied to logout after done on success screen
> 
>  a-success.mov

This issue is still there @surajeaton , could you please verify?

**Comment by surajeaton** [comment]
> > Noticed the change password dialog is open before its called from menu. If I cancel change password and logout from menu then log back in the change password dialog does not open at login. So might be tied to logout after done on success screen
> > a-success.mov
> 
> This issue is still there @surajeaton , could you please verify?

Fixed now. Please review.

**Pull request merged**
