### PR TITLE
Added reset password full screen

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4140

#### Changes proposed in this Pull Request:

- Added reset password full screen
- Added example

#### Screenshots / Screen Recording (if applicable)
Screenshot 2023-06-07 at 4 21 56 PM

#### To Test:
- yarn start:example2
- Click on Reset Password Full Screen

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by ektaghag-eaton — COMMENTED** [review]
Translation works.
Screenshot 2023-06-08 at 9 53 01 AM

**Review by ektaghag-eaton — COMMENTED** [review]
Changes are working fine 👍 . @surajeaton How to test Error dialog? Right now I set showError(true).

**Comment by surajeaton** [comment]
@ektaghag-eaton Yes, to test error dialog locally, setting showError(true) will be good.

**Review by ektaghag-eaton — APPROVED** [review]
Working fine 👍 .

**Pull request merged**
