### PR TITLE
Fix/update i18next version

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 
https://github.com/etn-ccis/blui-react-workflows/issues/233 
add line `i18nAppInstance.addResourceBundle('en', 'bluiCommon', { ACTIONS:{ CREATE_ACCOUNT: 'Register now!' }
}, true, true); ` in app.tsx of example file and check it should update text

#### Changes proposed in this Pull Request:

The app should run properly with all translations if we are not passing the i18n app instance to the i18n prop to auth context or registration context
- Custom screen translations should work in registration or auth workflow after passing the app i18n instance to context provider
`AuthContextProvider
                        actions={ProjectAuthUIActions(app)}
                        language={app.language}
                        navigate={navigate}
                        routeConfig={routes}
                        i18n={i18nAppInstance}
                        rememberMeDetails={{ email: rememberMe ? email : '', rememberMe: rememberMe }}
                    >
                        <Outlet />
                    </AuthContextProvider>`
- **Update typescript version to 5.2.2**
- **Update the Eslint version to the latest for fixing the below error**

Screenshot 2023-09-27 at 10 39 21 AM

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- Test all screens with translations
- Check the login page you should see the `Register Now!` text
- **You can use <CustomScreen/> in the registration workflow to see translations**

#### Any specific feedback you are looking for?

- **Typescript version is updated in this PR so please review all file changes to see what fixes I have added to remove type-checking errors.**

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
Please resolve the conflicts.

**Comment by ektaghag-eaton** [comment]
> Please resolve the conflicts.

Fixed @surajeaton , please review.

**Comment by JeffGreiner-eaton** [comment]
looks like some issue in forgot password screen base and props.

image

**Comment by ektaghag-eaton** [comment]
> looks like some issue in forgot password screen base and props.
> 
> image

Fixed it. @JeffGreiner-eaton please review.

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good to me, override working for our languages

**Comment by JeffGreiner-eaton** [comment]
@ektaghag-eaton please remove test code

**Pull request merged**
