### PR TITLE
Fix/4706 change pw dialog props

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 4706 .

#### Changes proposed in this Pull Request:

- fix currentPasswordChange, loading prop 
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- you can use this code snippet in login-workflow/example/src/components/ChangePassword.tsx
` <ChangePasswordDialog
            currentPasswordChange={(currentPassword: string) => {
                console.log('Print Current Password', currentPassword);
            }}
            loading={false}
            open={app.showChangePasswordDialog}
            onPrevious={(): void => app.setShowChangePasswordDialog(false)}
            onSubmit={(): void => app.setShowChangePasswordDialog(false)}
            onFinish={(): void => logOut()}
        />`

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
Please resolve the conflicts.

**Review by surajeaton — COMMENTED** [review]
Please resolve the conflicts.

**Comment by ektaghag-eaton** [comment]
> Please resolve the conflicts.

Done @surajeaton , please review.

**Review by daileytj — APPROVED** [review]
Looks good to me

**Pull request merged**
