### PR TITLE
Enhance customization of error messaging

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-4088.

Fixes BLUI-4401.

#### Changes proposed in this Pull Request:

- Add ErrorManager to remaining components
- Add useErrorManager hook
- Manage API errors via ErrorManager for all components that make API calls

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- add 
``` 
throw new Error('My Custom Error', {
    cause: {
        title: 'Custom Title',
        errorMessage: 'My custom error message',
    },
});
```
to the beginning of the corresponding auth or registration action so that an error is thrown and the corresponding component that calls that action will render the appropriate error. By default the error message will be rendered inside of an error dialog. In order to test the message box simple change the props via the AuthContextProvider or the RegistrationContextProvider as follows:
```
 <AuthContextProvider
                    ...
                     errorConfig={{
                        mode: 'message-box',
                        messageBoxConfig: {
                            dismissible: true,
                            position: 'top',
                        },
                    }}
                >
```
If you provide no customization it should default to a dialog error. Feel free to check out the types definition and mess around with all of the props to ensure they all work.

### CODE REVIEW

**Comment by daileytj** [comment]
@ektaghag-eaton I'm still trying to figure out one use case on the Eula screen, but aside from that this can be tested.

**Review by ektaghag-eaton — COMMENTED** [review]
I am using the code 
`
throw new Error('My Custom Error', {
            cause: {
                title: 'Error',
                errorMessage: 'Sorry, there was a problem sending your request.',
            },
        });
`
which you have mentioned in PR description for screens like forgot password (auth workflow) and account details (registration workflow) but it shows different error dialogs.

Forgot Password:
Screenshot 2023-07-20 at 3 06 53 PM

Account Details 
Screenshot 2023-07-20 at 3 06 32 PM

**Comment by ektaghag-eaton** [comment]
> I am using the code `throw new Error('My Custom Error', { cause: { title: 'Error', errorMessage: 'Sorry, there was a problem sending your request.', }, });` which you have mentioned in PR description for screens like forgot password (auth workflow) and account details (registration workflow) but it shows different error dialogs.
> 
> Forgot Password: Screenshot 2023-07-20 at 3 06 53 PM
> 
> Account Details Screenshot 2023-07-20 at 3 06 32 PM

Please ignore this comment understood now it is happening because of errorConfig 
https://github.com/etn-ccis/blui-react-workflows/pull/363/files#diff-7a84bbe311a68d6176321428d1b2fba793e6a968e85212691ecf2fdf1bb88423R23

**Review by ektaghag-eaton — COMMENTED** [review]
@daileytj , is it possible to set errorDisplayConfig prop to individual screen? If yes then it is not showing error message. I tried below code. 

Screenshot 2023-07-21 at 3 49 48 PM

**Comment by ektaghag-eaton** [comment]
Tried passing emailValidator prop working fine
Screenshot 2023-07-21 at 3 45 05 PM

**Comment by ektaghag-eaton** [comment]
I have tested all screens with errors working fine if I am passing error like you mentioned 
throw new Error('My Custom Error', {
    cause: {
        title: 'Custom Title',
        errorMessage: 'My custom error message',
    },
});

Please check  https://github.com/etn-ccis/blui-react-workflows/pull/363#pullrequestreview-1540796033

**Comment by daileytj** [comment]
> I have tested all screens with errors working fine if I am passing error like you mentioned throw new Error('My Custom Error', { cause: { title: 'Custom Title', errorMessage: 'My custom error message', }, });
> 
> Please check [#363 (review)](https://github.com/etn-ccis/blui-react-workflows/pull/363#pullrequestreview-1540796033)

You should be able to throw standard errors now as well. No need to check every location as they all essentially work the same, but it may be good to test a few where you just do something like ` throw new Error('Sorry, there was a problem sending your request.');`

**Comment by daileytj** [comment]
> @daileytj , is it possible to set errorDisplayConfig prop to individual screen? If yes then it is not showing error message. I tried below code.
> 
> Screenshot 2023-07-21 at 3 49 48 PM

I'm not sure if we're expecting to be able to manage the props this way. The full screen component reads from the errorManager hook which will always get the config from the authcontext. If you want to customize for each screen then you would have to customize the config on the wrapper AuthContextProvider for each screen.

**Comment by joebochill** [comment]
> I'm not sure if we're expecting to be able to manage the props this way. The full screen component reads from the errorManager hook which will always get the config from the authcontext. If you want to customize for each screen then you would have to customize the config on the wrapper AuthContextProvider for each screen.
> 
> edit: on second thought this probably should work. hmm.. I'll take a second look today. If everything is working otherwise, I would like to get this merged in and work on the missing pieces in the "final fixes" story so that this isn't sitting around while other work is done on components I touched. Just trying to avoid merge conflicts where possible.

If there is a prop for it on the screen components, it should work. You should be able to just modify the hook to take an argument for errorDisplayConfig and let the hook merge the properties with the values from the context. 

As a side note, the `useErrorContext` hook should probably return the default settings when there is no Provider in the hierarchy instead of throwing an error https://github.com/etn-ccis/blui-react-workflows/blob/dev/login-workflow/src/new-architecture/contexts/ErrorContext/index.ts#L16). This will allow the base screens to be used independent of a ContextProvider if desired.

**Comment by daileytj** [comment]
> > I'm not sure if we're expecting to be able to manage the props this way. The full screen component reads from the errorManager hook which will always get the config from the authcontext. If you want to customize for each screen then you would have to customize the config on the wrapper AuthContextProvider for each screen.
> > edit: on second thought this probably should work. hmm.. I'll take a second look today. If everything is working otherwise, I would like to get this merged in and work on the missing pieces in the "final fixes" story so that this isn't sitting around while other work is done on components I touched. Just trying to avoid merge conflicts where possible.
> 
> If there is a prop for it on the screen components, it should work. You should be able to just modify the hook to take an argument for errorDisplayConfig and let the hook merge the properties with the values from the context.
> 
> As a side note, the `useErrorContext` hook should probably return the default settings when there is no Provider in the hierarchy instead of throwing an error https://github.com/etn-ccis/blui-react-workflows/blob/dev/login-workflow/src/new-architecture/contexts/ErrorContext/index.ts#L16). This will allow the base screens to be used independent of a ContextProvider if desired.

I'm not sure I follow as the base screens can be used independently already; You would simply have to pass in your own config rather than letting the parent "full screen" manage it. I also believe the passing of the props is working as intended. We are double checking everything now.

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
