### PR TITLE
Feature/4714 update validate user registration request return type

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #  BLUI-4714

#### Changes proposed in this Pull Request:

- Updated validateUserRegistrationRequest action to return boolean or string
- Updated account already exists screen logic
- Updated code verify logic for both self / invite register

#### Screenshots / Screen Recording (if applicable)

- To test please change the return value from validateUserRegistrationRequest `{ codeValid: true, accountExists: false }`
1. Passing accountExists as true ---> Should show account already exists success screen
2. Passing codeValid as false or string ---> Should show error dialog
3. `accountExists` has more preference over `codeValid`

**Invite Registration**

https://github.com/etn-ccis/blui-react-workflows/assets/120575281/a6d1fda2-f622-4903-ad64-2a23432762f4

**Self Registration**

https://github.com/etn-ccis/blui-react-workflows/assets/120575281/98bacff8-3f14-4096-bc27-9af55b07b6a3

#### To Test:

- cd login-workflow
- Change the return values of validateUserRegistrationRequest

#### Any specific feedback you are looking for?

1. Passing accountExists as true ---> Should show account already exists success screen
2. Passing codeValid as false or string ---> Should show error dialog
3. `accountExists` has more preference over `codeValid`

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
when I set return { codeValid: true, accountExists: true }; I get account created. Should this be set to only one true and one false ?


https://github.com/etn-ccis/blui-react-workflows/assets/119693939/fa41b1ca-c43f-48f8-9638-0ad8135cbb2b

**Comment by surajeaton** [comment]
> when I set return { codeValid: true, accountExists: true }; I get account created.
> 
>  invite.mov

accountExists: true should show ExistingAccountSuccessScreen. The attached video is following the correct scenario.

**accountExists: true**  should always show ExistingAccountSuccessScreen regardless the value of ** codeValid**

**Comment by JeffGreiner-eaton** [comment]
when return { codeValid: false, accountExists: true };


https://github.com/etn-ccis/blui-react-workflows/assets/119693939/217ae4a6-4e51-43d4-9d7b-1296c0166954

**Review by JeffGreiner-eaton — APPROVED** [review]
codeValid, accountExists and string looks good

**Pull request merged**
