### PR TITLE
Feature/4339 update translations of all screens

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 4339 .

#### Changes proposed in this Pull Request:

- Update Translations of all screens
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- All screens

#### Any specific feedback you are looking for?

- Need to merge https://github.com/etn-ccis/blui-react-workflows/pull/305

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
@ektaghag-eaton is this ready for review?

**Comment by ektaghag-eaton** [comment]
> @ektaghag-eaton is this ready for review?

Yes @JeffGreiner-eaton , please review.

**Comment by ektaghag-eaton** [comment]
@JeffGreiner-eaton and @daileytj need inputs for the below texts. Shall I add translations in each file?

https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L61

https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L68

https://github.com/etn-ccis/blui-react-workflows/blob/1378c357b1b6061b5c4379aeb856c8fc814327b5/login-workflow/src/new-architecture/screens/ContactScreen/ContactScreenBase.tsx#L110 (Do I need to log an issue and fix this separately ?)

**Comment by JeffGreiner-eaton** [comment]
> @JeffGreiner-eaton and @daileytj need inputs for the below texts. Shall I add translations in each file?
> 
> https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L61
> 
> https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L68
> 
> https://github.com/etn-ccis/blui-react-workflows/blob/1378c357b1b6061b5c4379aeb856c8fc814327b5/login-workflow/src/new-architecture/screens/ContactScreen/ContactScreenBase.tsx#L110
> 
> (Do I need to log an issue and fix this separately ?)

if they are base component the hardcoded values can remain. If they are full component it should use verbiage from translations.

**Comment by ektaghag-eaton** [comment]
> > @JeffGreiner-eaton and @daileytj need inputs for the below texts. Shall I add translations in each file?
> > https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L61
> > 
> > https://github.com/etn-ccis/blui-react-workflows/blob/bd58c8df7e7b1fe93d496c82ca1808e0ee0c2fe5/login-workflow/src/new-architecture/screens/LoginScreen/LoginScreen.tsx#L68
> > 
> > https://github.com/etn-ccis/blui-react-workflows/blob/1378c357b1b6061b5c4379aeb856c8fc814327b5/login-workflow/src/new-architecture/screens/ContactScreen/ContactScreenBase.tsx#L110
> > 
> > (Do I need to log an issue and fix this separately ?)
> 
> if they are base component the hardcoded values can remain. If they are full component it should use verbiage from translations.

Both screens are full screens:


Screenshot 2023-06-23 at 11 59 04 AM

**Comment by manojleaton** [comment]
Contact Us screen is not fully translated

Screenshot 2023-06-23 at 1 40 33 PM

**Comment by JeffGreiner-eaton** [comment]
> 

this is the old original contact screen and it's not translated. I believe all input data is not translated. 
 
image

**Comment by JeffGreiner-eaton** [comment]
> 

Not sure what you mean, this file is base not full. unless I don't understand what you mean...
image

**Comment by ektaghag-eaton** [comment]
> Contact Us screen is not fully translated
> 
> Screenshot 2023-06-23 at 1 40 33 PM

Raised an issue https://github.com/etn-ccis/blui-react-workflows/issues/317

**Review by daileytj — APPROVED** [review]

**Pull request merged**
