### PR TITLE
Fix/bl UI 4704 create password prop

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 4704 .

#### Changes proposed in this Pull Request:

- Enabled next button initialNewPasswordValue and initialConfirmPasswordValue is already set
- Show an error when the password is not matched on the first load.
-

#### Screenshots / Screen Recording (if applicable)

- Enabled next button initialNewPasswordValue and initialConfirmPasswordValue is already set
Screenshot 2023-09-20 at 3 30 39 PM
- Show an error when the password is not matched on the first load.

Screenshot 2023-09-20 at 3 30 16 PM

#### To Test:

- Test code is available in AppRouter.tsx go to http://localhost:3000/self-registration
- Go to Create Password Screen

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
Prettier is faling.
Please run yarn prettier

**Review by daileytj — APPROVED** [review]
Looks good to me, just be sure to remove the test code prior to merging

**Review by surajeaton — COMMENTED** [review]
Please fix the failing test cases.

**Comment by ektaghag-eaton** [comment]
> Please fix the failing test cases.

Hi @surajeaton, I have fixed the test cases.

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good, just update appRouter

**Review by surajeaton — APPROVED** [review]
Looks good. Please undo the changes for testing.
Also, there are wrong js doc for both create password and base screen (referring to contact support screen), please update those.

**Pull request merged**
