### PR TITLE
Added context for RegistrationWorkflowContext and types

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4166

#### Changes proposed in this Pull Request:

- Added context for registration workflow context

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- Can not be tested as of now, until we have component ready

#### Any specific feedback you are looking for?

- Once this gets merged, please open #260 
- Changelog will be updated in the last PR

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
This looks good but we just had a conversation about adding a new src folder for all the new items we are building.
Can you create a new folder in login-workflow/src/"new-architecture" and everything else we fit in there.

**Comment by joebochill** [comment]
I also made a small tweak to the type definition in your story to be a bit more specific than Record<object>:
image

**Comment by surajeaton** [comment]
@joebochill @JeffGreiner-eaton Done. Please review.

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good

**Pull request merged**
